name: flutter_task_app
description: "Professional Flutter app with Clean Architecture + BLoC + TDD"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  equatable: ^2.0.7

  # DI
  get_it: ^9.2.0

  # Networking
  http: ^1.6.0
  connectivity_plus: ^7.0.0

  # Local storage
  shared_preferences: ^2.5.4

  # Utilities
  dartz: ^0.10.1
  uuid: ^4.5.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  #Testing 
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg

